openapi: 3.0.0
info:
  title: helpdesk API
  description: swagger API Document
  version: 0.0.1
servers:
  - url: http://localhost:3001/api/helpdesk    
paths:
  /getTicket?id={id}:
    get:
      get:
      summary: ticket.
      description: ticket detail
      parameters:
      - name: "id"
        in: "path"
        description: "ticket id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        '200':    # status code
          description: "success"        
  /listTicket:
    post:
      post:
      summary: list
      description: list ticket
      requestBody:      
        description: "{} for all record,status in (pending, accepted, resolved, rejected),order in (status,update_at)"          
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/listticket'
      responses:
        '200':    # status code
          description: "success"
  /saveTicket:      
    post:
      post:
      summary: add or update
      description: id==0 add new ticket else update by id
      requestBody:
        description: status in (pending, accepted, resolved, rejected)       
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/ticket'
      responses:
        '200':    # status code
          description: "success"

definitions:  

  ticket:
    type: object
    properties:
      id:
        type: integer
        description: ticket id
      title:
        type: string
        description:  title
      contract_info:
        type: string
        description: contract infomation
      description:
        type: string
        description: description
      status:
        type: string
        description: status    
  
  listticket:
    type: object
    properties:
      status:
        type: string
        description: pending, accepted, resolved, rejected
      order:
        type: string
        description: status, update_at